# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  api:
    image: api
    build:
      context: .
      dockerfile: src/API/Dockerfile
    ports:
      - 8080:8080


   # Redis service using the latest image from Docker Hub
  redis:
    image: redis:latest  # This pulls the latest Redis image
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis_data:/data  # Optional: Persists data

networks:
  app-network:
    driver: bridge


volumes:
  redis_data: